---

name: Test

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
      - 'requirements_test.txt'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
      - 'requirements_test.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r src/backend/map_generator/requirements.txt >/dev/null

      - name: Downloading libraries
        run: |
          wget https://github.com/O-X-L/opensimplex/releases/download/${NOISE_CLI_VERSION}/noise_cli_linux_amd64.zip
          unzip noise_cli_linux_amd64.zip
          mv noise_cli_linux_amd64 lib/noise_cli
          wget https://raw.githubusercontent.com/O-X-L/opensimplex/refs/heads/latest/opensimplex_cli.py -o lib/opensimplex_cli.py
        env:
          NOISE_CLI_VERSION: '0.1'

      - name: Running Unit Tests
        run: |
          python3 -m pytest --version
          python3 -m pytest

      - name: Running map-generator
        run: bash scripts/map-gen.sh
        env:
          GAME_MAP_CHUNKS: '1'
